services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - ./shared:/shared
    networks:
      - app-network

  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./service:/app
      - ./shared:/shared
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
      - service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge